spring:
  application:
    name: SensorDataConsumer
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: sensor-data-consumer-group
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
server:
  port: 8081
